name: Auto-merge enabler

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write
  contents: write

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_NUMBER"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
